mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.views.generic import TemplateView
from mysite import settings
from app.views import *
# from .api import api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('user.urls'), name='user'), # 用户
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')), # 引入ckeditor
    path('captcha/', include('captcha.urls')), # 验证码
    # path('', TemplateView.as_view(template_name='app/index.html')),
    path('', index, name='index'),
    path('recom/', item_pred, name='recom'),
    path('accept/<int:data_id>', accept, name='accept'),
    path('reject/<int:data_id>', dislike, name='reject'),
    # path("api/", api.urls), # 引入restful
    path("__debug__/", include("debug_toolbar.urls")), # 调试信息
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL) # 配置静态资源的路径

mysite/user/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('login/', user_login, name='login'),
    path('register/', register, name='register'), # 注册
    path('logout/', logout, name='logout'), # 退出
]

mysite/templates/base.html
{% load static %}
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link href="{% static 'bootstrap5/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'bootstrap5/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bootstrap5/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'jquery.3.5.min.js' %}"></script>
    
    <!-- 引入MDB -->
    <link rel="stylesheet" href="{% static 'MDB5-STANDARD-UI-KIT-Free-6.4.2/css/mdb.min.css' %}">
    <script src="{% static 'MDB5-STANDARD-UI-KIT-Free-6.4.2/js/mdb.min.js' %}"></script>
<!--     <link href="https://cdn.bootcdn.net/ajax/libs/layer/3.5.1/theme/default/layer.min.css" rel="stylesheet">
    <script src="https://cdn.bootcdn.net/ajax/libs/layer/3.5.1/layer.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script> -->
</head>
<!-- <script src="https://cdn.bootcdn.net/ajax/libs/echarts/5.0.2/echarts.min.js"></script> -->
<body>
    <script type="text/javascript">
        $(function(){
            $('table').addClass('table table-borderd table-striped table-sm');
            $('table thead tr').attr('style', '');
        });
    </script>
    <div class="container">
        {% include 'nav.html' %}
        <div class="mt-3">
            {% bootstrap_messages %}
        </div>
        <div class="mt-3">
        {% block content %}

        {% endblock %}
        </div>
    </div>
</body>
</html>

mysite/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">{{ site_name }}</a>
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="/">首页</a>
        <a class="nav-link active" aria-current="page" href="/admin/">数据管理</a>
        <a class="nav-link active" aria-current="page" href="/recom/">为您推荐</a>
      </div>
    </div>
    <div class="d-flex align-items-center">
      {% if request.user.is_authenticated %}
            <a class="nav-link" href="#">您好, {{ request.user.username }}</a> 
            <a class="btn btn-link px-2 me-2 btn-lg" href="{% url 'user:logout' %}">注销</a>
        {% else %}
            <a class="btn btn-link btn-lg" href="{% url 'user:login' %}">登录</a>
            <a class="btn btn-link btn-lg" href="{% url 'user:register' %}">注册</a>
        {% endif %}
    </div>
  </div>
</nav>